name = "libneo"
version = "0.3.0"
license = "MIT"
author = "Christopher Albert"
maintainer = "albert@tugraz.at"
copyright = "Copyright 2025, Plasma Physics at TU Graz"

[dependencies]
# System libraries (openmp, mpi, hdf5, netcdf) handled via compiler flags

[build]
external-modules = [
    "fftw3", "fftw3.f03",
    "netcdf", "hdf5", "h5lt",
    "omp_lib", "mpi", "mpi_f08",
    "openacc"
]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"
